### ISSUE TITLE
Set up communication channel for public transport community

### ISSUE THREAD

**Issue by AltNico** [public-transport/ideas#11]
At [35C3](https://en.wikipedia.org/wiki/Chaos_Communication_Congress) we (@ialokim, @schildbach, @derhuerst and others whose nicknames I don't know) did an extended public transport meeting, where the idea came up to set up a communication channel for the community around public transport projects built with open data and FLOSS.

The problem others described was that there are many people doing cool stuff with public transport, but it lacks communication between them which results in work being done multiple times. We thought that we could improve this by providing some form of communication channel which is not specific to one system, but rather a meta platform for everything related to public transport + open data + FLOSS.

The idea is that in this channel people could show up if they have questions like "Do you know an API to get transport data for this region?" or "Did someone ever built a service for this use case?". Also, people should be able to discuss problems they encounter when building stuff, announce projects they built, and do all other things one can imagine.

One problem we saw was that with the global scope of this channel it could become very noisy, with information getting quickly lost. In case this happens, I suggest to set up stuff like a wiki where information can get stored.

We also discussed the type of communication protocol to use. Please note that everything following now is out of my subjective perspective and doesn't have to be the consensus of that meet up. In my humble opinion, email lists don't suite the described use case well. Instead, chat rooms like [IRC](https://en.wikipedia.org/wiki/Internet_Relay_Chat), [Jabber/XMPP](https://xmpp.org/), [Matrix](https://matrix.org/blog/home/), [Telegram](https://telegram.org/) and others do. Let me propose a setup influenced by my role as a Matrix server operator for F-Droid:

_tl:dr: We set up a channel which is accessible via IRC, XMPP, Matrix and Telegram_

On [hackint.org](https://hackint.org/) we set up an IRC channel which gets [automatically bridged to Jabber/XMPP](https://hackint.org/transport/xmpp). On matrix.org we set up a room which gets bridged to that IRC channel at hackint. From that Matrix room we build a bridge to a Telegram group. Excepting the XMPP bridge, this is exactly the setup we use at F-Droid and it works pretty well for us for quite some time.

Coming from Matrix, we can build whatever bridge people would like to services like [Gitter](https://github.com/matrix-org/matrix-appservice-gitter) and [Slack](https://github.com/matrix-org/matrix-appservice-slack).

Maybe something like this already exists. If so, please post to this issue linking to more information.

Please notify other people who could be interested in this.

(Pinging people from MapaNica (@mayorgatellez, @porfiriopaiz, @roirobo, @xamanu, @xirapo) and _osm2gtfs_ (@jamescr, @grote, @nlehuby, @prhod, @nicolasiensen))

By the way, happy new year to everybody!

**Comment by derhuerst** [comment]
> Instead, chat rooms like [IRC](https://en.wikipedia.org/wiki/Internet_Relay_Chat), [Jabber/XMPP](https://xmpp.org/), [Matrix](https://matrix.org/blog/home/), [Telegram](https://telegram.org/) and others do. Let me propose a setup influenced by my role as a Matrix server operator for F-Droid:
>
> _tl:dr: We set up a channel which is accessible via IRC, XMPP, Matrix and Telegram_

I'm all for open (as in easily accessible and F(L)OSS) communication channels. Because there's a hosted Matrix instance already, I don't see any significant disadvantages in using it.

> On [hackint.org](https://hackint.org/) we set up an IRC channel which gets [automatically bridged to Jabber/XMPP](https://hackint.org/transport/xmpp). On matrix.org we set up a room which gets bridged to that IRC channel at hackint.

> Coming from Matrix, we can build whatever bridge people would like to services like [Gitter](https://github.com/matrix-org/matrix-appservice-gitter) and [Slack](https://github.com/matrix-org/matrix-appservice-slack).

Just, this would be very nice. There's a [public transport Slack](https://public-transport.slack.com/) and a [`public-transport` Gitter channel](https://gitter.im/public-transport/Lobby) we created a while ago that we should connect.

**Comment by schildbach** [comment]
@AltNico What's the Matrix room called?

**Comment by AltNico** [comment]
@schildbach So far there is no Matrix room. I opened this issue to discuss its creation together with rooms/groups/channels on other platforms.

**Comment by schildbach** [comment]
Ok, so count my :+1: towards a matrix room.

**Comment by schildbach** [comment]
I went ahead and created a Matrix room for everyone to join: `#public-transport:schildbach.de`

We can switch to a different room any time, I just wanted to start something so that we can stay in touch.

**Comment by AltNico** [comment]
For your interest, you can find a log of that room here: https://view.matrix.org/alias/%23public-transport:schildbach.de

**Comment by AltNico** [comment]
@derhuerst I've set up the Matrix-Gitter bridge. See the logs at [Gitter](https://gitter.im/public-transport/Lobby?at=5c33a2eb73360b4d55d28af3) and [Matrix](https://view.matrix.org/room/!uwcfVbmKhyHkftmlnL:schildbach.de/?anchor=$15468880631741cqYfd:dorfbrunnen.eu&highlight) ([alternative link](https://matrix.to/#/!uwcfVbmKhyHkftmlnL:schildbach.de/$15468880631741cqYfd:dorfbrunnen.eu)) for more information.

Are you still interested in a Slack bridge? How many people are in there?

**Comment by AltNico** [comment]
To all: [Hackint shutdown their Matrix bridge some days ago](https://hackint.org/#20181028_Matrix_Bridging_Sunset), so we would have to set up an IRC channel at some other host. Is there any interest at all in an IRC channel, bridged to that room?

**Comment by d3d9** [comment]
I would use a Telegram bridge, can that be set up?

**Comment by AltNico** [comment]
@d3d9 Sure! Although, I would need your help with this as I don't have Telegram myself. Can you please
* create a Telegram group
* invite `@matrix_t2bot` into it
* type `/id` and paste the output here in this issue

according to [this instructions](https://t2bot.io/telegram)? I'll then handle the Matrix part.

**Comment by AltNico** [comment]
I just saw that people can even [use email](https://t2bot.io/email) to chat with us. So if anyone is interested in that, ping me!

**Comment by d3d9** [comment]
@AltNico -270052894

**Comment by AltNico** [comment]
@d3d9 Thanks. The bridge is set up and you should have received our messages.

How can people in Telegram join that room? Did you give it an ID?

**Comment by d3d9** [comment]
It has the ID @public_transport, the public link https://t.me/public_transport can be used

**Comment by ialokim** [comment]
I think the information about the chatroom should be added to the readme.

**Comment by AltNico** [comment]
@ialokim You're right, see https://github.com/public-transport/ideas/issues/12.
