### ISSUE TITLE
Add information about chat in readme

### ISSUE THREAD

**Issue by AltNico** [public-transport/ideas#12]
In #11 we set up a chat which is synced across Matrix and Gitter and open to other networks through bridges. @ialokim suggested to add information about this chat in the readme, to which I agree.

**Comment by ialokim** [comment]
The gitter chat is already mentioned, but we should add the [Telegram](https://t.me/public_transport) and the matrix (`#public-transport:schildbach.de`) "entrypoints" too.

**Comment by derhuerst** [comment]
I'm having trouble to generate a [shields.io](https://shields.io/) badge for the Matrix room: I used `public-transport` as "room alias" and `schildbach.de` as FQDN/server, but it says "not found".

```
https://img.shields.io/matrix/public-transport.svg?server_fqdn=schildbach.de&style=flat
```

![public-transport Matrix room](https://img.shields.io/matrix/public-transport.svg?server_fqdn=schildbach.de&style=flat)

**Comment by ialokim** [comment]
Surely, @schildbach's matrix server has a configuration as follows:
> Some Matrix homeservers don't hold a server name matching where they live (e.g. if the homeserver example.com that created the room alias #mysuperroom:example.com lives at matrix.example.com).

As I don't know the FQDN address, it's producing the same "not found" for me.

Luckily, our room also has an alias over at `matrix.org` so the following does works:

`https://img.shields.io/matrix/public-transport:matrix.org.svg?style=flat`

![](https://img.shields.io/matrix/public-transport:matrix.org.svg?style=flat)

**Comment by schildbach** [comment]
The room id is `#public-transport:schildbach.de`. The matrix server is lives on is `matrix.schildbach.de`. The connection between the two is done via DNS as per matrix spec:
```
$ dig -t srv _matrix._tcp.schildbach.de
[...]
_matrix._tcp.schildbach.de. 3600 IN	SRV	10 0 8448 matrix.schildbach.de.
```
